### ISSUE TITLE
How to change Text color

### ISSUE THREAD

**Issue by rajeevjaiswal** [GoodieBag/Pinview#3]
@Vatican-Cameos I am not able to change the color of the input text as well as for hint. Please let me know how this can be done

**Comment by ShrikantBadwaik-007** [comment]
I'm also facing same issue, there is no attribute to set text color. Please help

**Comment by raghunandankavi2010** [comment]
instead of creating edittext on the fly create a layout with edittext and then inflate the same  and add it to the list.

`
    private void createEditTexts() {
        removeAllViews();
        editTextList.clear();
        EditText editText;
        LayoutInflater inflater = (LayoutInflater) mContext.getSystemService( Context.LAYOUT_INFLATER_SERVICE );
        for (int i = 0; i < mPinLength; i++) {
            editText  =(EditText) inflater.inflate(R.layout.edittext_view,null);
            //editText = view.findViewById(R.id.editText);

            editTextList.add(i, editText);
            this.addView(editText);
            generateOneEditText(editText, "" + i);
        }
        setTransformation();
    }`

**Comment by vaibhav0786** [comment]
please add full description

**Comment by Vatican-Cameos** [comment]
Fixed in v1.4

**Comment by JagadishaIncture** [comment]
how to change hint color?

no java Method found
