### ISSUE TITLE
how to reduce space between pins

### ISSUE THREAD

**Issue by ShrikantBadwaik-007** [GoodieBag/Pinview#5]
Hi, i want to add 6 pins but layout gets disturbed. How do i reduce space between pins?
Thanks

**Comment by KoderKrishanu** [comment]
The space between two pins is determined by `splitWidth`.
in xml use `app:splitWidth` in java use `setSplitWidth` 

To reduce the size of the pins try to set `pinWidth` & `pinHeight` via xml or java

Defaults
---------
splitWidth : 20dp
pinWidth : 50dp
pinHeight : 50dp

**Comment by ShrikantBadwaik-007** [comment]
that will do, thanks
