### ISSUE TITLE
Not alble to set value in setValue() method?

### ISSUE THREAD

**Issue by Niks345** [GoodieBag/Pinview#6]
Hi, i used your pineview and its working but i want to reset the value in pinview on button click,how should i do that? i use to set the value as 0000 by calling setvalue() method but it problem is when i called getValue() after that i get only 0000 not the user enter value after reset, please help me.

**Comment by arberg** [comment]
I have added that ability to the source and fixed a problem where setValue("") did not work for numbers. You can find the source here: https://github.com/arberg/Pinview

**Comment by Niks345** [comment]
How can i update that in my code?

**Comment by aravindechobound** [comment]
Git pull this code - https://github.com/arberg/Pinview. Add the pinview as module within the Android Studio project ('File' > 'New Module') and provide source as 'pinview' directory. Update the 'pinview' module Gradle file according to the target compile version for your project and add 'pinview' dependency to your target module Gradle file. The usage for pinview widget will remain same post that.

**Comment by Vatican-Cameos** [comment]
@arberg I have merged Alex's pull request. 
The setValue will work in the next release. 
Thanks Alex and sorry for the inconvenience caused.
Closing the issue.
